sudo: required
services:
    - docker 
before_install:
    - docker build -t pbadgujarns/react-test -f ./client/Dockerfile.dev ./client 
    # - docker build -t pbadgujarns/react-test -f ./client/Dockerfile.dev ./client 

script:
    - docker run -e CI=true pbadgujarns/react-test npm test

after_success:
    - docker build -t miththoobhai/multi-client ./client 
    - docker build -t miththoobhai/multi-nginx ./nginx
    - docker build -t miththoobhai/multi-server ./server 
    - docker build -t miththoobhai/multi-worker ./worker 
    #Log in to docker CLI
    - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
    #push images to docker hub
    - docker push miththoobhai/multi-client
    - docker push miththoobhai/multi-nginx
    - docker push miththoobhai/multi-server
    - docker push miththoobhai/multi-worker

deploy:
    edge:true
    provider: elasticbeanstalk 
    region: us-west-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-west-2-721357086872
    bucket_path: docker-multi
    on:
        branch: master    
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

